version: '2'
services:
  aplicacao-teste:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - redeteste
    volumes:
      - log:/reservonibus/log.txt

volumes:
  log:

networks:
  redeteste:
    driver: bridge